name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug Files
        run: |
          ls -al

      - name: Debug SSH Key Secret
        run: |
          echo "EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}"
          echo "HOST_DNS: ${{ secrets.HOST_DNS }}"
          echo "USERNAME: ${{ secrets.USERNAME }}"

      - name: Deploy to EC2        
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
        run: |     
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
            
          scp -i ${{ secrets.EC2_SSH_KEY }} -r * ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:/home/ubuntu/
          ssh -i ${{ secrets.EC2_SSH_KEY }} ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} "cd /home/ubuntu/app && python3 index.py"
