name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug Files
        run: |
          ls -al

      - name: Debug SSH Key Secret
        run: |
          echo "EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}"
          echo "HOST_DNS: ${{ secrets.HOST_DNS }}"
          echo "USERNAME: ${{ secrets.USERNAME }}"

      - name: Debug SSH Key File Presence
        run: |
          # Construct the full path to the private key file
          PRIVATE_KEY_PATH="/github/home/${{ secrets.EC2_SSH_KEY }}"
    
          # Display the contents of the directory
          ls -la "${PRIVATE_KEY_PATH}"

          # Display the content of the private key (masked)
          echo "EC2_SSH_KEY: ***"



      - name: Deploy to EC2
        run: |          
          scp -i ${{ env.SSH_PRIVATE_KEY }} -r * ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }}:/home/ubuntu/
          ssh -i ${{ env.SSH_PRIVATE_KEY }} ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }} "cd /home/ubuntu/app && python3 index.py"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          
